
interface LeadersProps {
     bio: string;
     title: string;
     name: string;
     image: string;
}

export const leaders: LeadersProps[] = [
        { image: "/images/jatin.webp", name: "JATIN S. BAINS", title: "Founder & CEO", bio: "40 years experience across the maritime and supply chain verticals. He represented USA on maritime security at the 2006 Hanoi APEC conference. He is the creator of our military-grade CATE™ System and holds a USPTO patent on eLogistics. He attended the Wharton Management Program, national security courses, ISR certifications and subject matter expert to US DoD." },
        { image: "/images/dylan.webp", name: "DYLAN MONROE", title: "COO/CPTO", bio: "Dylan Monroe is a leader in AI, machine learning, automation, and geospatial intelligence with over a decade of experience at NASA, USDA, Inspire Brands, and in the private sector. At NASA, he led 50 developers on 150+ projects using satellite data for environmental monitoring, earning the 2024 CDO Award for Innovation. With 10+ certifications, Dylan has advanced agricultural intelligence and automation, delivering data-driven solutions across sectors." },
        { image: "/images/aiden.webp", name: "AIDEN JOHNSON", title: "Chief Data Scientist", bio: "Aiden Johnson boasts over a decade of experience in machine learning and artificial intelligence, specializing in scalable solutions within the AWS environment. His expertise lies in integrating data from diverse sources, including IoT sensor data and satellite imagery." },
        { image: "/images/arthur.webp", name: "ARTHUR J. MADJARIAN", title: "Sr. V.P. & Global Head of Sales", bio: "As part of Space-Eyes' leadership, he oversees global sales and partnerships, driving the company’s go-to-market strategy across government, defense, and enterprise sectors. With over $250M in career transactions, he connects advanced space-based technologies to real-world challenges, positioning Space-Eyes as a leader in space-based predictions for disasters, trade security, and national security." },
        { image: "/images/joe.webp", name: "JOE EL RADY", title: "CFO", bio: "Joe El Rady is a seasoned financial executive with over a decade of experience in consulting, capital raising, and strategic planning across real estate, healthcare, and tech. As VP of Finance at SoLa Impact, he leads operations and portfolio management, building on prior experience managing a $1.2B project at a private equity firm headed by former U.S. Secretary of Defense Frank Carlucci. He holds an MBA from Wharton and an honors degree from Stanford." },
        { image: "/images/rakesh.webp", name: "RAKESH AGHI", title: "Strategic Growth Advisor", bio: "With over 35 years of leadership in precision manufacturing, Rakesh Aghi is a seasoned executive and entrepreneur who founded Cobra Carbide and Advanced Coating Technologies. He has established his companies as premier U.S.-based suppliers of critical tools and advanced coatings for the defense and aerospace sectors, serving clients like NASA and SpaceX. Rakesh is recognized for his expertise in strengthening the domestic supply chain and navigating complex government contracting" },
        { image: "/images/payton.webp", name: "HONORABLE SUE C. PAYTON", title: "Former Assistant Secretary of the US Air Force/Acquisition", bio: "Sue Payton’s government service and role as AF Acquisition Executive provide expertise in acquisition, R&D, and tech transition, with insights into ground/space systems from her work at Lockheed Martin." },
        { image: "/images/keating1.webp", name: "ADMIRAL TIMOTHY J. KEATING", title: "USN (Retired)", bio: "Admiral Keating’s career includes roles as Commander of U.S. Pacific Command and U.S. Northern Command, focusing on security and stability through engagement with national and international partners." },
        { image: "/images/kevin.webp", name: "GENERAL KEVIN P. CHILTON", title: "USAF (Retired)", bio: "General Chilton’s 34.5-year Air Force career included commanding U.S. Strategic Command, overseeing nuclear, space, and cyberspace operations. His NASA astronaut experience adds to his aerospace and defense expertise." },
        { image: "/images/harbir1.webp", name: "PROFESSOR Dr. HARBIR SINGH", title: "Mack Professor of Management at Wharton, University of Pennsylvania.", bio: "Dr. Harbir Singh is Co-Director of Wharton’s Mack Institute and Vice Dean for Global Initiatives, with research interests in corporate governance, restructuring, joint ventures, buyouts, and acquisitions." }
];

